---
title: "Poisson Distribution"
author: "SS Huh"
date: '2020 12 2 '
output: html_document
---

## 포아송분포 정의 - 이산형

일반적으로 매우 희귀하여 일어날 확률이 아주 작은 경우에 적용되는데, 확률변수 X가 세가지 조건(독립성, 비집락성, 비례성)을 만족할 때 성공의 평균 출현횟수를 m이라하면 확률함수는 다음과 같다.
$$
P(X=x)=\frac{m ^{x}}{x!} e^{-m}
$$
이때 E(X)=m, Var(X)=m이다.

## 적률생성함수

$$
M(t)=E(e^{tX})=\sum_{x=0}^{}e^{tx}\cdot P(X)=\sum_{x=0}^{}e^{tx}\cdot \frac{m ^{x}}{x!} e^{-m}=e^{-m}\sum_{x=0}^{} \frac{(me^t) ^{x}}{x!}=e^{m(exp(t)-1)}
$$

## 기대값(평균)
$$
E(x)=\sum_{r=0}^{n}r\cdot P(X)=\sum_{r=0}^{n}r\cdot\frac{m ^{r}}{r!} e^{-m}=e^{-m}\cdot\sum_{r=1}^{n}\frac{m\cdot m ^{r-1}}{(r-1)!} =m\cdot e^{-m}\sum_{r=1}^{n}\frac{ m ^{r-1}}{(r-1)!}=m\cdot e^{-m} e^m =m
$$
## 분산
$$
E(x^2)=\sum_{r=0}^{n}r^2\cdot P(X)=\sum_{r=0}^{n}r^2 \cdot\frac{m ^{r}}{r!} e^{-m}=e^{-m}\cdot\sum_{r=1}^{n}r\cdot\frac{m ^{r}}{(r-1)!} = e^{-m}\sum_{r=1}^{n}\frac{(r-1+1) m ^{r}}{(r-1)!}=e^{-m}\sum_{r=1}^{n}\frac{(r-1) m ^{r}+m ^{r}}{(r-1)!}
$$
$$
=e^{-m}\left[\sum_{r=2}^{n}\frac{m ^{r}}{(r-2)!}+\sum_{r=1}^{n}\frac{m ^{r}}{(r-1)!}\right] =e^{-m}\left[\sum_{r=2}^{n}\frac{m^2 m ^{r-2}}{(r-2)!}+\sum_{r=1}^{n}\frac{m m ^{r-1}}{(r-1)!}\right] =e^{-m}(m^2 e^m+me^m)=m^2+m
$$
$$
\therefore Var(X)=E(X^2)-E(X)^2=(m^2+m)-(m)^2=m
$$

##예제01
어떤 주차장에 매 10분 단위로 평균 1대의 차가 주차를 위해 들어온다고 가정할 때 한시간 동안 주차를 위해 들어오는 차의 숫자가 3대 이하일 확률을 구하라
```{r}
#10분마다 1대 이므로 1시간 동안의 평균값 m=6이 된다.
ppois(3,6)
```

##예제02
1860명의 보험계약자를 보유하고 있는 화재보험회사가 있다. 1년에 화재 발생으로 보험료 청구하는 확률이 1/600 이라면 어느 해에 화재보험금을 청구하는 횟수가 3명 이하일 확률은?
```{r}
n=1860
p=1/600
m=n*p

dpois(0,m) #P(X=0)
dpois(1,m) #P(X=1)
dpois(2,m) #P(X=2)
dpois(3,m) #P(X=3)
```
##예제03
은행에서 하루 평균 6건의 불량수표를 받게 된다고 할 때 어떤 특정한 날에 불량수표를 4번 받을 확률은?
```{r}
m=6
x=4
dpois(x,m)
```

